name: execute workflow commands
on: push
jobs:
   Run:
    runs-on: ubuntu-latest
    steps:
      - name: Create annotation for build error
        run: echo "::error file=app.js,line=1::Missing semicolon"
      - name: setting a debug message
        run: echo "::debug::Set the Octocat variable"

